ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = HOSPITAL;

CREATE TABLE appointment_status_history 
    ( 
     id             NUMBER (12) GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     appointment_id VARCHAR2 (36)  NOT NULL , 
     status_id      VARCHAR2 (20)  NOT NULL , 
     changed_by     VARCHAR2 (36) , 
     changed_at     TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL , 
     note           VARCHAR2 (500) 
    ) 
    LOGGING 
;

ALTER TABLE appointment_status_history 
    ADD CONSTRAINT appointment_status_history_PK PRIMARY KEY ( id ) ;

CREATE TABLE appointment_statuses 
    ( 
     status_id   VARCHAR2 (20)  NOT NULL , 
     status_name VARCHAR2 (100)  NOT NULL , 
     sort_order  NUMBER (4) DEFAULT 0  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE appointment_statuses 
    ADD CONSTRAINT appointment_statuses_PK PRIMARY KEY ( status_id ) ;

CREATE TABLE appointment_types 
    ( 
     type_id              VARCHAR2 (20)  NOT NULL , 
     type_name            VARCHAR2 (100)  NOT NULL , 
     default_duration_min NUMBER (4)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE appointment_types 
    ADD CONSTRAINT chk_types_duration 
    CHECK (default_duration_min > 0)
;
ALTER TABLE appointment_types 
    ADD CONSTRAINT appointment_types_PK PRIMARY KEY ( type_id ) ;

CREATE TABLE appointments 
    ( 
     appointment_id   VARCHAR2 (36)  NOT NULL , 
     patient_id       VARCHAR2 (36)  NOT NULL , 
     doctor_id        VARCHAR2 (36)  NOT NULL , 
     department_id    VARCHAR2 (36)  NOT NULL , 
     room_id          VARCHAR2 (36) , 
     type_id          VARCHAR2 (20)  NOT NULL , 
     status_id        VARCHAR2 (20)  NOT NULL , 
     follow_up_id     VARCHAR2 (36) , 
     appointment_date DATE  NOT NULL , 
     time_start       CHAR (5) , 
     time_end         CHAR (5) , 
     duration_min     NUMBER (4) , 
     notes            VARCHAR2 (1000) , 
     cancel_reason    VARCHAR2 (500) , 
     room_no          VARCHAR2 (20) , 
     created_by       VARCHAR2 (36) , 
     created_at       TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL , 
     updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL 
    ) 
    LOGGING 
;
CREATE INDEX idx_appt_patient ON appointments 
    ( 
     patient_id ASC 
    ) 
;
CREATE INDEX idx_appt_doctor ON appointments 
    ( 
     doctor_id ASC 
    ) 
;
CREATE INDEX idx_appt_dept ON appointments 
    ( 
     department_id ASC 
    ) 
;
CREATE INDEX idx_appt_room ON appointments 
    ( 
     room_id ASC 
    ) 
;
CREATE INDEX idx_appt_type ON appointments 
    ( 
     type_id ASC 
    ) 
;
CREATE INDEX idx_appt_status ON appointments 
    ( 
     status_id ASC 
    ) 
;

ALTER TABLE appointments 
    ADD CONSTRAINT chk_duration_pos 
    CHECK (duration_min IS NULL OR duration_min > 0)
;


ALTER TABLE appointments 
    ADD CONSTRAINT chk_time_hhmi_end 
    CHECK (time_end IS NULL OR REGEXP_LIKE(time_end, '^[0-2][0-9]:[0-5][0-9]$'))
;


ALTER TABLE appointments 
    ADD CONSTRAINT chk_time_hhmi_start 
    CHECK (time_start IS NULL OR REGEXP_LIKE(time_start, '^[0-2][0-9]:[0-5][0-9]$'))
;
ALTER TABLE appointments 
    ADD CONSTRAINT appointments_PK PRIMARY KEY ( appointment_id ) ;

CREATE TABLE appointments_audit 
    ( 
     appt_audit_id  NUMBER (12) GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     appointment_id VARCHAR2 (36)  NOT NULL , 
     action         VARCHAR2 (30)  NOT NULL , 
     changed_by     VARCHAR2 (36) , 
     changed_at     TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL , 
     old_data       CLOB , 
     new_data       CLOB 
    ) 
    LOGGING 
;

ALTER TABLE appointments_audit 
    ADD CONSTRAINT chk_appt_audit_action 
    CHECK (action IN ('INSERT','UPDATE','DELETE'))
;


ALTER TABLE appointments_audit 
    ADD CONSTRAINT chk_appt_audit_new_json 
    CHECK (new_data IS NULL OR new_data IS JSON)
;


ALTER TABLE appointments_audit 
    ADD CONSTRAINT chk_appt_audit_old_json 
    CHECK (old_data IS NULL OR old_data IS JSON)
;
ALTER TABLE appointments_audit 
    ADD CONSTRAINT appointments_audit_PK PRIMARY KEY ( appt_audit_id ) ;

CREATE TABLE departments 
    ( 
     department_id VARCHAR2 (36)  NOT NULL , 
     dept_name     VARCHAR2 (100)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE departments 
    ADD CONSTRAINT departments_PK PRIMARY KEY ( department_id ) ;

CREATE TABLE doctors 
    ( 
     doctor_id     VARCHAR2 (36)  NOT NULL , 
     full_name     VARCHAR2 (150)  NOT NULL , 
     license_no    VARCHAR2 (50)  NOT NULL , 
     phone         VARCHAR2 (10) , 
     specialty     VARCHAR2 (100) , 
     department_id VARCHAR2 (36) 
    ) 
    LOGGING 
;
CREATE INDEX idx_doctor_dept ON doctors 
    ( 
     department_id ASC 
    ) 
;

ALTER TABLE doctors 
    ADD CONSTRAINT doctors_PK PRIMARY KEY ( doctor_id ) ;

ALTER TABLE doctors 
    ADD CONSTRAINT INDEX_1 UNIQUE ( license_no ) ;

CREATE TABLE patients 
    ( 
     patient_id VARCHAR2 (36)  NOT NULL , 
     hn         VARCHAR2 (20)  NOT NULL , 
     first_name VARCHAR2 (100) , 
     last_name  VARCHAR2 (100) , 
     dob        DATE , 
     phone      VARCHAR2 (10) , 
     email      VARCHAR2 (150) 
    ) 
    LOGGING 
;

ALTER TABLE patients 
    ADD CONSTRAINT patients_PK PRIMARY KEY ( patient_id ) ;

ALTER TABLE patients 
    ADD CONSTRAINT INDEX_1 UNIQUE ( hn ) ;

CREATE TABLE patients_audit 
    ( 
     pat_audit_id NUMBER (12) GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     patient_id   VARCHAR2 (36)  NOT NULL , 
     action       VARCHAR2 (30)  NOT NULL , 
     changed_at   TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL , 
     old_data     CLOB , 
     new_data     CLOB 
    ) 
    LOGGING 
;

ALTER TABLE patients_audit 
    ADD CONSTRAINT chk_pat_audit_action 
    CHECK (action IN ('INSERT','UPDATE','DELETE'))
;


ALTER TABLE patients_audit 
    ADD CONSTRAINT chk_pat_audit_new_json 
    CHECK (new_data IS NULL OR new_data IS JSON)
;


ALTER TABLE patients_audit 
    ADD CONSTRAINT chk_pat_audit_old_json 
    CHECK (old_data IS NULL OR old_data IS JSON)
;
ALTER TABLE patients_audit 
    ADD CONSTRAINT patients_audit_PK PRIMARY KEY ( pat_audit_id ) ;

CREATE TABLE rooms 
    ( 
     room_id       VARCHAR2 (36)  NOT NULL , 
     department_id VARCHAR2 (36)  NOT NULL , 
     room_name     VARCHAR2 (100)  NOT NULL , 
     location_desc VARCHAR2 (200) 
    ) 
    LOGGING 
;

ALTER TABLE rooms 
    ADD CONSTRAINT rooms_PK PRIMARY KEY ( room_id ) ;

CREATE TABLE visits 
    ( 
     visit_id       VARCHAR2 (36)  NOT NULL , 
     appointment_id VARCHAR2 (36) , 
     checkin_at     TIMESTAMP , 
     checkout_at    TIMESTAMP 
    ) 
    LOGGING 
;

ALTER TABLE visits 
    ADD CONSTRAINT visits_PK PRIMARY KEY ( visit_id ) ;

ALTER TABLE visits 
    ADD CONSTRAINT INDEX_1 UNIQUE ( appointment_id ) ;

ALTER TABLE appointments_audit 
    ADD CONSTRAINT fk_appt_audit_appt FOREIGN KEY 
    ( 
     appointment_id
    ) 
    REFERENCES appointments 
    ( 
     appointment_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE appointments 
    ADD CONSTRAINT fk_appt_dept FOREIGN KEY 
    ( 
     department_id
    ) 
    REFERENCES departments 
    ( 
     department_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE appointments 
    ADD CONSTRAINT fk_appt_doctor FOREIGN KEY 
    ( 
     doctor_id
    ) 
    REFERENCES doctors 
    ( 
     doctor_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE appointments 
    ADD CONSTRAINT fk_appt_followup FOREIGN KEY 
    ( 
     follow_up_id
    ) 
    REFERENCES appointments 
    ( 
     appointment_id
    ) 
    ON DELETE SET NULL 
    NOT DEFERRABLE 
;

ALTER TABLE appointments 
    ADD CONSTRAINT fk_appt_patient FOREIGN KEY 
    ( 
     patient_id
    ) 
    REFERENCES patients 
    ( 
     patient_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE appointments 
    ADD CONSTRAINT fk_appt_room FOREIGN KEY 
    ( 
     room_id
    ) 
    REFERENCES rooms 
    ( 
     room_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE appointments 
    ADD CONSTRAINT fk_appt_status FOREIGN KEY 
    ( 
     status_id
    ) 
    REFERENCES appointment_statuses 
    ( 
     status_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE appointments 
    ADD CONSTRAINT fk_appt_type FOREIGN KEY 
    ( 
     type_id
    ) 
    REFERENCES appointment_types 
    ( 
     type_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE doctors 
    ADD CONSTRAINT fk_doctor_department FOREIGN KEY 
    ( 
     department_id
    ) 
    REFERENCES departments 
    ( 
     department_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE appointment_status_history 
    ADD CONSTRAINT fk_hist_appt FOREIGN KEY 
    ( 
     appointment_id
    ) 
    REFERENCES appointments 
    ( 
     appointment_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE appointment_status_history 
    ADD CONSTRAINT fk_hist_stat FOREIGN KEY 
    ( 
     status_id
    ) 
    REFERENCES appointment_statuses 
    ( 
     status_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE patients_audit 
    ADD CONSTRAINT fk_pat_audit_pat FOREIGN KEY 
    ( 
     patient_id
    ) 
    REFERENCES patients 
    ( 
     patient_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE rooms 
    ADD CONSTRAINT fk_rooms_department FOREIGN KEY 
    ( 
     department_id
    ) 
    REFERENCES departments 
    ( 
     department_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE visits 
    ADD CONSTRAINT fk_visit_appt FOREIGN KEY 
    ( 
     appointment_id
    ) 
    REFERENCES appointments 
    ( 
     appointment_id
    ) 
    NOT DEFERRABLE 
;

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = HOSPITAL;

--------------------------------------------------------------------------------
-- Appointment Statuses
--------------------------------------------------------------------------------
MERGE INTO appointment_statuses t
USING (SELECT 'S001' AS status_id, 'Scheduled' AS status_name, 1 AS sort_order FROM dual) s
ON (t.status_id = s.status_id)
WHEN MATCHED THEN 
  UPDATE SET t.status_name = s.status_name, t.sort_order = s.sort_order
WHEN NOT MATCHED THEN 
  INSERT (status_id, status_name, sort_order)
  VALUES (s.status_id, s.status_name, s.sort_order);

MERGE INTO appointment_statuses t
USING (SELECT 'S002' AS status_id, 'Completed' AS status_name, 2 AS sort_order FROM dual) s
ON (t.status_id = s.status_id)
WHEN MATCHED THEN 
  UPDATE SET t.status_name = s.status_name, t.sort_order = s.sort_order
WHEN NOT MATCHED THEN 
  INSERT (status_id, status_name, sort_order)
  VALUES (s.status_id, s.status_name, s.sort_order);

MERGE INTO appointment_statuses t
USING (SELECT 'S003' AS status_id, 'Cancelled' AS status_name, 3 AS sort_order FROM dual) s
ON (t.status_id = s.status_id)
WHEN MATCHED THEN 
  UPDATE SET t.status_name = s.status_name, t.sort_order = s.sort_order
WHEN NOT MATCHED THEN 
  INSERT (status_id, status_name, sort_order)
  VALUES (s.status_id, s.status_name, s.sort_order);

--------------------------------------------------------------------------------
-- Appointment Types
--------------------------------------------------------------------------------
INSERT INTO appointment_types (type_id, type_name, default_duration_min)
SELECT 'T001','นัดตรวจทั่วไป',30 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM appointment_types WHERE type_id='T001');

INSERT INTO appointment_types (type_id, type_name, default_duration_min)
SELECT 'T002','นัดติดตามอาการ',20 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM appointment_types WHERE type_id='T002');

INSERT INTO appointment_types (type_id, type_name, default_duration_min)
SELECT 'T003','นัดฉีดวัคซีน',10 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM appointment_types WHERE type_id='T003');

INSERT INTO appointment_types (type_id, type_name, default_duration_min)
SELECT 'T004','นัดทำหัตถการ',200 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM appointment_types WHERE type_id='T004');

--------------------------------------------------------------------------------
-- Departments
--------------------------------------------------------------------------------
INSERT INTO departments (department_id, dept_name)
SELECT 'D001','อายุรกรรม' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE department_id='D001');

INSERT INTO departments (department_id, dept_name)
SELECT 'D002','กุมารเวชกรรม' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE department_id='D002');

INSERT INTO departments (department_id, dept_name)
SELECT 'D003','หู คอ จมูก' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE department_id='D003');

INSERT INTO departments (department_id, dept_name)
SELECT 'D004','ศัลยกรรมกระดูก' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE department_id='D004');

INSERT INTO departments (department_id, dept_name)
SELECT 'D005','สูติ-นรีเวช' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM departments WHERE department_id='D005');

--------------------------------------------------------------------------------
-- Rooms
--------------------------------------------------------------------------------
INSERT INTO rooms (room_id, department_id, room_name, location_desc)
SELECT 'R001','D001','ห้องตรวจอายุรกรรมทั่วไป', NULL FROM dual
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_id='R001');

INSERT INTO rooms (room_id, department_id, room_name, location_desc)
SELECT 'R002','D002','ห้องตรวจเด็ก', NULL FROM dual
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_id='R002');

INSERT INTO rooms (room_id, department_id, room_name, location_desc)
SELECT 'R003','D003','ห้องตรวจหู คอ จมูก', NULL FROM dual
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_id='R003');

INSERT INTO rooms (room_id, department_id, room_name, location_desc)
SELECT 'R004','D004','ห้องตรวจศัลยกรรมกระดูก', NULL FROM dual
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_id='R004');

INSERT INTO rooms (room_id, department_id, room_name, location_desc)
SELECT 'R005','D005','ห้องตรวจสูติ-นรีเวช', NULL FROM dual
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_id='R005');

INSERT INTO rooms (room_id, department_id, room_name, location_desc)
SELECT 'R006','D001','ห้องตรวจอายุรกรรมทั่วไป 2', NULL FROM dual
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_id='R006');

INSERT INTO rooms (room_id, department_id, room_name, location_desc)
SELECT 'R007','D002','ห้องตรวจเด็ก 2', NULL FROM dual
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_id='R007');

INSERT INTO rooms (room_id, department_id, room_name, location_desc)
SELECT 'R008','D003','ห้องตรวจหู คอ จมูก 2', NULL FROM dual
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_id='R008');

INSERT INTO rooms (room_id, department_id, room_name, location_desc)
SELECT 'R009','D004','ห้องตรวจศัลยกรรมกระดูก 2', NULL FROM dual
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_id='R009');

INSERT INTO rooms (room_id, department_id, room_name, location_desc)
SELECT 'R010','D005','ห้องตรวจสูติ-นรีเวช 2', NULL FROM dual
WHERE NOT EXISTS (SELECT 1 FROM rooms WHERE room_id='R010');

--------------------------------------------------------------------------------
-- Doctors (DOC001..DOC005)  -- หมายเหตุ: มี UNIQUE(license_no)
--------------------------------------------------------------------------------
INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC001','Dr.Beam Nini','MD12345','0812345678','อายุรกรรมทั่วไป','D001' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC001');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC002','Dr.Twin Terbo','MD23456','0823456789','กุมารเวชกรรม','D002' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC002');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC003','Dr.Pond Ontherock','MD34567','0834567890','หู คอ จมูก','D003' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC003');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC004','Dr.Sed Vegan','MD45678','0845678901','ศัลยกรรมกระดูก','D004' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC004');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC005','Dr.Sho Palangbai','MD56789','0856789012','สูติ-นรีเวช','D005' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC005');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC006','Dr.Phat Internal','MD67890','0867890123','อายุรกรรมทั่วไป','D001' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC006');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC007','Dr.May Clinic','MD67891','0878901234','อายุรกรรมทั่วไป','D001' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC007');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC008','Dr.Aim Peds','MD67892','0889012345','กุมารเวชกรรม','D002' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC008');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC009','Dr.Korn ENT','MD67893','0890123456','หู คอ จมูก','D003' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC009');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC010','Dr.Nam ENT','MD67894','0801234567','หู คอ จมูก','D003' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC010');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC011','Dr.Pim ENT','MD67895','0819876543','หู คอ จมูก','D003' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC011');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC012','Dr.Boss Ortho','MD67896','0829876543','ศัลยกรรมกระดูก','D004' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC012');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC013','Dr.Fah Ortho','MD67897','0839876543','ศัลยกรรมกระดูก','D004' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC013');

INSERT INTO doctors (doctor_id, full_name, license_no, phone, specialty, department_id)
SELECT 'DOC014','Dr.June OB-GYN','MD67898','0849876543','สูติ-นรีเวช','D005' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE doctor_id='DOC014');

--------------------------------------------------------------------------------
-- Patients (PAT001..PAT005)  -- หมายเหตุ: มี UNIQUE(hn)
--------------------------------------------------------------------------------
INSERT INTO patients (patient_id, hn, first_name, last_name, dob, phone, email)
SELECT 'PAT001','HN0001','ชิษณุพงษ์','คงควรคอย', DATE '2002-07-12','0992384822', 'chit.mail' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM patients WHERE patient_id='PAT001');

INSERT INTO patients (patient_id, hn, first_name, last_name, dob, phone, email)
SELECT 'PAT002','HN0002','คงกระพัน','ยันหว่าง', DATE '1995-03-12','0912345678', 'kong.mail' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM patients WHERE patient_id='PAT002');

INSERT INTO patients (patient_id, hn, first_name, last_name, dob, phone, email)
SELECT 'PAT003','HN0003','เสดทะวุด','ทรุดโทรม', DATE '1988-07-21','0923456789', 'sed.mail' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM patients WHERE patient_id='PAT003');

INSERT INTO patients (patient_id, hn, first_name, last_name, dob, phone, email)
SELECT 'PAT004','HN0004','จีราวัฒน์','วัดได้', DATE '2000-01-05','0934567890', 'G.mail' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM patients WHERE patient_id='PAT004');

INSERT INTO patients (patient_id, hn, first_name, last_name, dob, phone, email)
SELECT 'PAT005','HN0005','สหพล','ชนแก้ว', DATE '1992-09-09','0945678901', 'saha.mail' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM patients WHERE patient_id='PAT005');

--------------------------------------------------------------------------------
COMMIT;

CREATE OR REPLACE VIEW rooms_by_department AS
SELECT
  d.department_id,
  d.dept_name,
  r.room_id,
  r.room_name,
  r.location_desc
FROM rooms r
JOIN departments d ON d.department_id = r.department_id;

--หมอของแต่ละแผนก
CREATE OR REPLACE VIEW doctors_by_department AS
SELECT
  d.department_id,
  d.dept_name,
  doc.doctor_id,
  doc.full_name AS doctor_name,
  doc.specialty
FROM doctors doc
LEFT JOIN departments d ON d.department_id = doc.department_id;

--คนไข้ตามใบนัดของแต่ละแผนก
CREATE OR REPLACE VIEW patients_appointments_by_department AS
SELECT
  dept.department_id,
  dept.dept_name,
  appt.appointment_id,
  appt.appointment_date,
  appt.time_start,
  appt.time_end,
  p.patient_id,
  (p.first_name || ' ' || p.last_name) AS patient_name
FROM appointments appt
JOIN departments dept ON dept.department_id = appt.department_id
JOIN patients p ON p.patient_id = appt.patient_id;

--ผู้ป่วยที่นัดโดยหมอ
CREATE OR REPLACE VIEW patients_by_doctor_name AS
SELECT
  doc.doctor_id,
  doc.full_name AS doctor_name,
  appt.appointment_id,
  appt.appointment_date,
  appt.time_start,
  appt.time_end,
  p.patient_id,
  (p.first_name || ' ' || p.last_name) AS patient_name
FROM appointments appt
JOIN doctors doc ON doc.doctor_id = appt.doctor_id
JOIN patients p  ON p.patient_id  = appt.patient_id;
--สถานะการนัดหมายของผู้ป่วย
CREATE OR REPLACE VIEW patient_appointment_status AS
SELECT
  p.patient_id,
  (p.first_name || ' ' || p.last_name) AS patient_name,
  appt.appointment_id,
  appt.appointment_date,
  appt.time_start,
  appt.time_end,
  s.status_name
FROM appointments appt
JOIN patients p ON p.patient_id = appt.patient_id
JOIN appointment_statuses s ON s.status_id = appt.status_id;

--ประวัติสถานะของการนัดหมาย
CREATE OR REPLACE VIEW appointment_status_history_view AS
SELECT
  h.id AS history_id,
  h.appointment_id,
  s.status_id,
  s.status_name,
  h.changed_by,
  h.changed_at,
  h.note
FROM appointment_status_history h
JOIN appointment_statuses s ON s.status_id = h.status_id;
-- จำนวนคนหมอของแต่ละแผนก
CREATE OR REPLACE VIEW department_doctor_counts AS
SELECT
  d.department_id,
  d.dept_name,
  COUNT(doc.doctor_id) AS total_doctors
FROM departments d
LEFT JOIN doctors doc
  ON doc.department_id = d.department_id
GROUP BY d.department_id, d.dept_name;

-- จำนวนคนไข้ของแต่ละแผนก
CREATE OR REPLACE VIEW department_patient_counts AS
SELECT
  d.department_id,
  d.dept_name,
  COUNT(DISTINCT a.patient_id) AS total_patients
FROM departments d
LEFT JOIN doctors doc
  ON doc.department_id = d.department_id
LEFT JOIN appointments a
  ON a.doctor_id = doc.doctor_id
GROUP BY d.department_id, d.dept_name;

-- แผนกที่มีจำนวนหมอมากที่สุด
CREATE OR REPLACE VIEW department_with_most_doctors AS
SELECT d.department_id,
       d.dept_name,
       COUNT(doc.doctor_id) AS total_doctors
FROM departments d
JOIN doctors doc ON d.department_id = doc.department_id
GROUP BY d.department_id, d.dept_name
HAVING COUNT(doc.doctor_id) = (
    SELECT MAX(cnt)
    FROM (
        SELECT COUNT(doctor_id) AS cnt
        FROM doctors
        GROUP BY department_id
    )
);

-- View: แผนกที่มีจำนวนผู้ป่วยมากที่สุด
CREATE OR REPLACE VIEW department_with_most_patients AS
SELECT d.department_id,
       d.dept_name,
       COUNT(DISTINCT a.patient_id) AS total_patients
FROM departments d
JOIN doctors doc ON d.department_id = doc.department_id
JOIN appointments a ON doc.doctor_id = a.doctor_id
GROUP BY d.department_id, d.dept_name
HAVING COUNT(DISTINCT a.patient_id) = (
    SELECT MAX(cnt)
    FROM (
        SELECT COUNT(DISTINCT a2.patient_id) AS cnt
        FROM departments d2
        JOIN doctors doc2 ON d2.department_id = doc2.department_id
        JOIN appointments a2 ON doc2.doctor_id = a2.doctor_id
        GROUP BY d2.department_id
    )
);

--ใบนัดที่ Complete แล้ว
CREATE OR REPLACE VIEW appointments_completed AS
SELECT
  appt.appointment_id,
  appt.appointment_date,
  appt.time_start,
  appt.time_end,
  d.full_name AS doctor_name,
  (p.first_name || ' ' || p.last_name) AS patient_name,
  dept.dept_name,
  r.room_name
FROM appointments appt
JOIN appointment_statuses s ON s.status_id = appt.status_id
JOIN doctors d      ON d.doctor_id = appt.doctor_id
JOIN patients p     ON p.patient_id = appt.patient_id
JOIN departments dept ON dept.department_id = appt.department_id
LEFT JOIN rooms r   ON r.room_id = appt.room_id
WHERE s.status_name = 'Completed';

--ใบนัดที่ Cancel แล้ว
CREATE OR REPLACE VIEW appointments_cancelled AS
SELECT
  appt.appointment_id,
  appt.appointment_date,
  appt.time_start,
  appt.time_end,
  d.full_name AS doctor_name,
  (p.first_name || ' ' || p.last_name) AS patient_name,
  dept.dept_name,
  r.room_name,
  appt.cancel_reason
FROM appointments appt
JOIN appointment_statuses s ON s.status_id = appt.status_id
JOIN doctors d      ON d.doctor_id = appt.doctor_id
JOIN patients p     ON p.patient_id = appt.patient_id
JOIN departments dept ON dept.department_id = appt.department_id
LEFT JOIN rooms r   ON r.room_id = appt.room_id
WHERE s.status_name = 'Cancelled';